In [1]:
import yfinance as yf
import numpy as np
import pandas as pd
import random

In [3]:
stocks = ["AAPL", "AMAT", "MSFT", "AMZN"]

data = yf.download(stocks, start="2026-02-20", end="2026-03-01")

data

[*********************100%***********************]  4 of 4 completed

Price            Close                                            High  \
Ticker            AAPL        AMAT        AMZN        MSFT        AAPL
Date
2026-02-20  264.579987  375.380005  210.110001  397.230011  264.750000
2026-02-23  266.179993  373.549988  205.270004  384.470001  269.429993
2026-02-24  272.140015  377.929993  208.559998  389.000000  274.890015
2026-02-25  274.230011  394.950012  210.639999  400.600006  274.940002
2026-02-26  272.950012  375.720001  207.919998  401.720001  276.109985
2026-02-27  264.179993  372.299988  210.000000  392.739990  272.809998

Price                                                  Low              \
Ticker            AMAT        AMZN        MSFT        AAPL        AMAT
Date
2026-02-20  377.109985  211.169998  400.119995  258.160004  366.269989
2026-02-23  378.859985  208.429993  395.359985  263.380005  369.679993
2026-02-24  380.510010  210.360001  389.359985  267.709991  368.000000
2026-02-25  395.950012  211.589996  401.470001  271.049988  384.000000
2026-02-26  393.470001  211.050003  407.489990  270.799988  366.540009
2026-02-27  378.579987  210.330002  396.820007  262.890015  365.609985

Price                                     Open                          \
Ticker            AMZN        MSFT        AAPL        AMAT        AMZN
Date
2026-02-20  203.750000  395.160004  258.970001  366.269989  204.759995
2026-02-23  203.110001  383.100006  263.489990  372.399994  208.100006
2026-02-24  203.250000  381.709991  267.859985  376.589996  205.470001
2026-02-25  208.929993  390.160004  271.779999  385.000000  210.460007
2026-02-26  205.350006  398.739990  274.950012  391.799988  210.729996
2026-02-27  205.199997  389.880005  272.809998  365.940002  206.830002

Price                     Volume
Ticker            MSFT      AAPL     AMAT      AMZN      MSFT
Date
2026-02-20  396.109985  42070500  8178700  65881600  34015200
2026-02-23  395.000000  37308200  6077400  53581500  43238300
2026-02-24  384.140015  47014600  5711800  41137200  33884700
2026-02-25  390.529999  33714300  9745000  41346400  43625500
2026-02-26  404.709991  32345100  7717100  47756800  34405900
2026-02-27  390.880005  72366500  9041400  57422800  51367200

In [3]:
stocks = ["AAPL", "AMAT", "MSFT", "AMZN"]
users = list(range(1, 51))  # 50 users

portfolio = {(user, stock): 0 for user in users for stock in stocks}

all_trades = []

for stock in stocks:
    df = yf.download(stock, start="2025-03-01", end="2026-03-01")
    df.columns = df.columns.get_level_values(0)
    df = df.reset_index()
    df["Date"] = pd.to_datetime(df["Date"])

    for _, row in df.iterrows():
        date = row["Date"]
        price = float(row["Close"])

        for _ in range(random.randint(10, 30)):
            user = random.choice(users)
            holding = portfolio[(user, stock)]

            # decide side safely
            if holding == 0:
                side = "Buy"
            else:
                side = random.choices(["Buy", "Sell"], weights=[0.6, 0.4])[0]

            # generate quantity properly
            if side == "Buy":
                quantity = random.randint(1, 50)
                portfolio[(user, stock)] += quantity

            else:  # SELL
                quantity = random.randint(1, holding)  
                portfolio[(user, stock)] -= quantity

            trade = {
                "user_id": user,
                "stock": stock,
                "price": round(price * random.uniform(0.98, 1.02), 2),
                "quantity": quantity,
                "side": side,
                "timestamp": date
            }

            all_trades.append(trade)

trades_df = pd.DataFrame(all_trades)
trades_df.to_csv("data.csv", index=False)

[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed
[*********************100%***********************]  1 of 1 completed

In [4]:
df = pd.read_csv("data.csv")
df

       user_id stock   price  quantity  side   timestamp
0           28  AAPL  239.27        24   Buy  2025-03-03
1           36  AAPL  233.90        48   Buy  2025-03-03
2           49  AAPL  236.72        34   Buy  2025-03-03
3           17  AAPL  233.41        49   Buy  2025-03-03
4           18  AAPL  234.44        19   Buy  2025-03-03
...        ...   ...     ...       ...   ...         ...
20356       27  AMZN  209.83         6   Buy  2026-02-27
20357       21  AMZN  212.72        50   Buy  2026-02-27
20358       29  AMZN  210.95        26   Buy  2026-02-27
20359       47  AMZN  212.75         8  Sell  2026-02-27
20360       29  AMZN  206.19        99  Sell  2026-02-27

[20361 rows x 6 columns]